fixed indents

diff --git a/scripts/copy_pkg b/scripts/copy_pkg
--- a/scripts/copy_pkg
+++ b/scripts/copy_pkg
@@ -23,22 +23,22 @@ case $1 in
     "mrover_arm_in")
         # check that source directories exist
         if [ ! -d ../mrover_arm ]; then
-        echo "Error: mrover_arm package doesn't exist in catkin_ws/src/"
-        exit 1
+            echo "Error: mrover_arm package doesn't exist in catkin_ws/src/"
+            exit 1
         fi
 
         if [ ! -d ../mrover_arm/rover_description/ ]; then
-        echo "Error: mrover_arm package is missing rover_description/"
-        exit 1
+            echo "Error: mrover_arm package is missing rover_description/"
+            exit 1
         fi
 
         # remove existing directories
         if [ -d src/teleop/mrover_arm/ ]; then
-        rm -r src/teleop/mrover_arm/
+            rm -r src/teleop/mrover_arm/
         fi
 
         if [ -d rover_description/arm/ ]; then
-        rm -r rover_description/arm/
+            rm -r rover_description/arm/
         fi
 
         # copy directories
@@ -50,18 +50,18 @@ case $1 in
     "mrover_arm_out")
         # check that source directories exist
         if [ ! -d src/teleop/mrover_arm/ ]; then
-        echo "Error: mrover_arm/ directory doesn't exist in src/teleop/"
-        exit 1
+            echo "Error: mrover_arm/ directory doesn't exist in src/teleop/"
+            exit 1
         fi
 
         if [ ! -d rover_description/arm/ ]; then
-        echo "Error: arm/ directory doesn't exist in rover_description/"
-        exit 1
+            echo "Error: arm/ directory doesn't exist in rover_description/"
+            exit 1
         fi
 
         # remove existing package
         if [ -d ../mrover_arm/ ]; then
-        rm -r ../mrover_arm/
+            rm -r ../mrover_arm/
         fi
 
         # copy directories
@@ -72,22 +72,22 @@ case $1 in
     "sa_arm_in")
         # check that source directories exist
         if [ ! -d ../mrover_sa_arm/ ]; then
-        echo "Error: mrover_sa_arm package doesn't exist in catkin_ws/src/"
-        exit 1
+            echo "Error: mrover_sa_arm package doesn't exist in catkin_ws/src/"
+            exit 1
         fi
 
         if [ ! -d ../mrover_sa_arm/rover_description/ ]; then
-        echo "Error: mrover_sa_arm package is missing rover_description/"
-        exit 1
+            echo "Error: mrover_sa_arm package is missing rover_description/"
+            exit 1
         fi
 
         # remove existing directories
         if [ -d src/teleop/mrover_sa_arm/ ]; then
-        rm -r src/teleop/mrover_sa_arm/
+            rm -r src/teleop/mrover_sa_arm/
         fi
 
         if [ -d rover_description/sa_arm/ ]; then
-        rm -r rover_description/sa_arm/
+            rm -r rover_description/sa_arm/
         fi
 
         # copy directories
@@ -99,18 +99,18 @@ case $1 in
     "sa_arm_out")
         # check that source directories exist
         if [ ! -d src/teleop/mrover_sa_arm/ ]; then
-        echo "Error: mrover_sa_arm/ directory doesn't exist in src/teleop/"
-        exit 1
+            echo "Error: mrover_sa_arm/ directory doesn't exist in src/teleop/"
+            exit 1
         fi
 
         if [ ! -d rover_description/sa_arm/ ]; then
-        echo "Error: sa_arm/ directory doesn't exist in rover_description/"
-        exit 1
+            echo "Error: sa_arm/ directory doesn't exist in rover_description/"
+            exit 1
         fi
 
         # remove existing package
         if [ -d ../mrover_sa_arm/ ]; then
-        rm -r ../mrover_sa_arm/
+            rm -r ../mrover_sa_arm/
         fi
 
         # copy directories
