changed indent size to 4

diff --git a/scripts/copy_pkg b/scripts/copy_pkg
--- a/scripts/copy_pkg
+++ b/scripts/copy_pkg
@@ -6,116 +6,116 @@
 set -Eeuo pipefail
 
 if [ ${PWD##*/} != "mrover" ]; then
-  echo "Error: script should be run only from the mrover pkg"
+    echo "Error: script should be run only from the mrover pkg"
 fi
 
 usage() {
-  echo "Usage: $0 (mrover_arm_in|mrover_arm_in|sa_arm_in|sa_arm_out)"
+    echo "Usage: $0 (mrover_arm_in|mrover_arm_in|sa_arm_in|sa_arm_out)"
 }
 
 if [ $# -ne 1 ]; then
-  usage
-  exit 1
+    usage
+    exit 1
 fi
 
 # Parse argument.  $1 is the first argument
 case $1 in
-  "mrover_arm_in")
-    # check that source directories exist
-    if [ ! -d ../mrover_arm ]; then
-      echo "Error: mrover_arm package doesn't exist in catkin_ws/src/"
-      exit 1
-    fi
+    "mrover_arm_in")
+        # check that source directories exist
+        if [ ! -d ../mrover_arm ]; then
+        echo "Error: mrover_arm package doesn't exist in catkin_ws/src/"
+        exit 1
+        fi
 
-    if [ ! -d ../mrover_arm/rover_description/ ]; then
-      echo "Error: mrover_arm package is missing rover_description/"
-      exit 1
-    fi
+        if [ ! -d ../mrover_arm/rover_description/ ]; then
+        echo "Error: mrover_arm package is missing rover_description/"
+        exit 1
+        fi
 
-    # remove existing directories
-    if [ -d src/teleop/mrover_arm/ ]; then
-      rm -r src/teleop/mrover_arm/
-    fi
+        # remove existing directories
+        if [ -d src/teleop/mrover_arm/ ]; then
+        rm -r src/teleop/mrover_arm/
+        fi
 
-    if [ -d rover_description/arm/ ]; then
-      rm -r rover_description/arm/
-    fi
+        if [ -d rover_description/arm/ ]; then
+        rm -r rover_description/arm/
+        fi
 
-    # copy directories
-    cp -r ../mrover_arm/. src/teleop/mrover_arm/
-    cp -r src/teleop/mrover_arm/rover_description/. rover_description/arm/
-    rm -r src/teleop/mrover_arm/rover_description/
-    ;;
+        # copy directories
+        cp -r ../mrover_arm/. src/teleop/mrover_arm/
+        cp -r src/teleop/mrover_arm/rover_description/. rover_description/arm/
+        rm -r src/teleop/mrover_arm/rover_description/
+        ;;
 
-  "mrover_arm_out")
-    # check that source directories exist
-    if [ ! -d src/teleop/mrover_arm/ ]; then
-      echo "Error: mrover_arm/ directory doesn't exist in src/teleop/"
-      exit 1
-    fi
+    "mrover_arm_out")
+        # check that source directories exist
+        if [ ! -d src/teleop/mrover_arm/ ]; then
+        echo "Error: mrover_arm/ directory doesn't exist in src/teleop/"
+        exit 1
+        fi
 
-    if [ ! -d rover_description/arm/ ]; then
-      echo "Error: arm/ directory doesn't exist in rover_description/"
-      exit 1
-    fi
+        if [ ! -d rover_description/arm/ ]; then
+        echo "Error: arm/ directory doesn't exist in rover_description/"
+        exit 1
+        fi
 
-    # remove existing package
-    if [ -d ../mrover_arm/ ]; then
-      rm -r ../mrover_arm/
-    fi
+        # remove existing package
+        if [ -d ../mrover_arm/ ]; then
+        rm -r ../mrover_arm/
+        fi
 
-    # copy directories
-    cp -r src/teleop/mrover_arm/. ../mrover_arm/
-    cp -r rover_description/arm/. ../mrover_arm/rover_description/
-    ;;
+        # copy directories
+        cp -r src/teleop/mrover_arm/. ../mrover_arm/
+        cp -r rover_description/arm/. ../mrover_arm/rover_description/
+        ;;
 
-  "sa_arm_in")
-    # check that source directories exist
-    if [ ! -d ../mrover_sa_arm/ ]; then
-      echo "Error: mrover_sa_arm package doesn't exist in catkin_ws/src/"
-      exit 1
-    fi
+    "sa_arm_in")
+        # check that source directories exist
+        if [ ! -d ../mrover_sa_arm/ ]; then
+        echo "Error: mrover_sa_arm package doesn't exist in catkin_ws/src/"
+        exit 1
+        fi
 
-    if [ ! -d ../mrover_sa_arm/rover_description/ ]; then
-      echo "Error: mrover_sa_arm package is missing rover_description/"
-      exit 1
-    fi
+        if [ ! -d ../mrover_sa_arm/rover_description/ ]; then
+        echo "Error: mrover_sa_arm package is missing rover_description/"
+        exit 1
+        fi
 
-    # remove existing directories
-    if [ -d src/teleop/mrover_sa_arm/ ]; then
-      rm -r src/teleop/mrover_sa_arm/
-    fi
+        # remove existing directories
+        if [ -d src/teleop/mrover_sa_arm/ ]; then
+        rm -r src/teleop/mrover_sa_arm/
+        fi
 
-    if [ -d rover_description/sa_arm/ ]; then
-      rm -r rover_description/sa_arm/
-    fi
+        if [ -d rover_description/sa_arm/ ]; then
+        rm -r rover_description/sa_arm/
+        fi
 
-    # copy directories
-    cp -r ../mrover_sa_arm/. src/teleop/mrover_sa_arm/
-    cp -r src/teleop/mrover_sa_arm/rover_description/. rover_description/sa_arm/
-    rm -r src/teleop/mrover_sa_arm/rover_description/
-    ;;
+        # copy directories
+        cp -r ../mrover_sa_arm/. src/teleop/mrover_sa_arm/
+        cp -r src/teleop/mrover_sa_arm/rover_description/. rover_description/sa_arm/
+        rm -r src/teleop/mrover_sa_arm/rover_description/
+        ;;
 
-  "sa_arm_out")
-    # check that source directories exist
-    if [ ! -d src/teleop/mrover_sa_arm/ ]; then
-      echo "Error: mrover_sa_arm/ directory doesn't exist in src/teleop/"
-      exit 1
-    fi
+    "sa_arm_out")
+        # check that source directories exist
+        if [ ! -d src/teleop/mrover_sa_arm/ ]; then
+        echo "Error: mrover_sa_arm/ directory doesn't exist in src/teleop/"
+        exit 1
+        fi
 
-    if [ ! -d rover_description/sa_arm/ ]; then
-      echo "Error: sa_arm/ directory doesn't exist in rover_description/"
-      exit 1
-    fi
+        if [ ! -d rover_description/sa_arm/ ]; then
+        echo "Error: sa_arm/ directory doesn't exist in rover_description/"
+        exit 1
+        fi
 
-    # remove existing package
-    if [ -d ../mrover_sa_arm/ ]; then
-      rm -r ../mrover_sa_arm/
-    fi
+        # remove existing package
+        if [ -d ../mrover_sa_arm/ ]; then
+        rm -r ../mrover_sa_arm/
+        fi
 
-    # copy directories
-    cp -r src/teleop/mrover_sa_arm/. ../mrover_sa_arm/
-    cp -r rover_description/sa_arm/. ../mrover_sa_arm/rover_description/
-    ;;
+        # copy directories
+        cp -r src/teleop/mrover_sa_arm/. ../mrover_sa_arm/
+        cp -r rover_description/sa_arm/. ../mrover_sa_arm/rover_description/
+        ;;
 
 esac
